### ISSUE TITLE
Agregar AppLayout Panel Usuario

### ISSUE THREAD

**Issue by Mry3ll0w** [EviLAsRz/IW2023-2024-OMW#19]

**Comment by Mry3ll0w** [comment]
Agregada la version inicial del layout para el panel de empleados, en desarrollo la del panel de usuarios

**Comment by EviLAsRz** [comment]
Versión inicial del panel de usuarios

**Comment by EviLAsRz** [comment]
Cambiar route para que reciba más de un Layout
