### ISSUE TITLE
Recuperacion de password

### ISSUE THREAD

**Issue by Mry3ll0w** [EviLAsRz/IW2023-2024-OMW#24]

**Comment by EviLAsRz** [comment]
Core del servidor SMTP realizado. 
Queda generar un botón dentro del LoginForm para habilitar al usuario la recuperación de la contraseña.
Testear la generación de correo.

**Comment by EviLAsRz** [comment]
Vista y conexion de rutas creada.
Falta la lógica del email.

**Comment by EviLAsRz** [comment]
Conexión correcta.
Falta generar código de recuperación de contraseña y personalizar el cuerpo del email.

**Comment by EviLAsRz** [comment]
Generación de token único de usuario listo.
Falta la incorporación de este para verificar al usuario.

**Comment by EviLAsRz** [comment]
Bugs arreglados
