### ISSUE TITLE
SonarQube en entorno de desarrollo

### ISSUE THREAD

**Issue by DoctorRuinoso** [EviLAsRz/IW2023-2024-OMW#31]
Una vez probado en entorno de prueba, se despliega junto al resto de componentes del proyecto para su posterior uso.

**Comment by Mry3ll0w** [comment]
Procedemos al migrado de MySQL a PostgreSQL por requisitos de SonarQube

**Comment by Mry3ll0w** [comment]
Migrado a postgres, nos ponemos con sonar

**Comment by Mry3ll0w** [comment]
Sonarqube instalado en docker y funcionando.
![Captura de pantalla 2024-01-02 a las 18 27 40](https://github.com/EviLAsRz/IW2023-2024-OMW/assets/48240649/849e9d98-1d84-4858-9166-68a3ec927104)
