### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by EviLAsRz** [EviLAsRz/IW2023-2024-OMW#7]
Crear una página para registrar a los usuarios, anteriormente autorizados por un formulario.

**Comment by Mry3ll0w** [comment]
Agregadas los campos principales basicos del registro para crear un usuario base, estando el mismo definido por el campo username que se corresponde al DNI, se plantea preparar el registro en forma de acordeon para hacerlo mas "bonito".
Falta completar los campos necesarios para definir la entidad cliente y contrato, al igual que gestionar su creacion.

**Comment by Mry3ll0w** [comment]
Todo listo, se propone una hacer formal el contrato por parte de un empleado.
